// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqtcsdnluspesklzorea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdGNzZG5sdXNwZXNrbHpvcmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTU4NDMsImV4cCI6MjA2NzczMTg0M30.1pqBhBNGb-_8adZXNfhtCv5FFLCxUVVy29MugBUV9DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});